version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    container_name: todos
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todos
    volumes:
      - todos:/var/lib/postgresql/data
volumes:
  todos: